import { MotionDiv, Reveal } from "@/components/Motion";
import { aiInsights, dashboards, faqs, industries, integrations, modules, outcomes, pricing, replacementSystems } from "@/lib/site-data";
import { SectionHeader } from "./SectionHeader";

export function TrustSection() {
  return <section className="px-6 py-20"><Reveal className="mx-auto max-w-7xl"><p className="text-center text-sm font-bold uppercase tracking-[.2em] text-muted">Trusted by teams running complex workforces</p><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-6">{["Aster", "Northstar", "Helio", "Vertex", "Kinetic", "Mosaic"].map((l) => <div className="glass rounded-2xl py-6 text-center text-xl font-black text-slate-500" key={l}>{l}</div>)}</div><div className="mt-8 grid gap-4 md:grid-cols-3">{[["42%", "faster employee case resolution"], ["3.8x", "recruiting throughput increase"], ["99.9%", "operating layer availability"]].map((s) => <div key={s[0]} className="rounded-3xl bg-ink p-8 text-white"><b className="text-4xl">{s[0]}</b><p className="mt-2 text-white/65">{s[1]}</p></div>)}</div></Reveal></section>;
}

export function ProblemSection() {
  return <section className="px-6 py-24"><SectionHeader eyebrow="The operating gap" title="Modern companies run on disconnected systems. Leadership pays the price." text="HR closes cases in one product. Payroll reconciles in another. Recruiting works from a separate pipeline. Finance exports reports. By the time leadership sees the picture, the business has already moved." /><Reveal className="mx-auto max-w-6xl rounded-[2.5rem] bg-white p-6 shadow-card"><div className="grid gap-4 md:grid-cols-[.9fr_1.1fr]"><div className="rounded-3xl bg-slate-50 p-8"><p className="text-sm font-black uppercase tracking-[.2em] text-muted">Before BAMS</p><h3 className="mt-4 text-3xl font-black">Every department owns a different version of the company.</h3><p className="mt-4 leading-7 text-muted">People data, payroll data, hiring data, customer activity, documents, and approvals drift apart. Teams work harder, but the company gets less clear.</p></div><div className="grid gap-3">{["HR uses one employee record.", "Payroll verifies another dataset.", "Recruiting forecasts demand manually.", "Executives wait for compiled reporting."].map((line, i) => <div key={line} className="flex items-center gap-4 rounded-2xl border border-slate-100 bg-white p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 font-black text-brand-600">{i + 1}</span><p className="font-semibold">{line}</p></div>)}</div></div></Reveal></section>;
}

export function PlatformSection() {
  return <section id="platform" className="px-6 py-24"><SectionHeader eyebrow="One platform" title="BAMS replaces the fragmented workforce software stack." text="The platform centers every module around BAMS Core: a governed company graph for people, payroll, recruiting, collaboration, analytics, and AI." /><Reveal className="mx-auto max-w-6xl rounded-[2.5rem] bg-gradient-to-br from-white to-brand-50 p-6 shadow-glow"><div className="grid gap-4 md:grid-cols-3"><div className="grid gap-3">{replacementSystems.slice(0,3).map((x) => <SystemNode key={x} label={x} />)}</div><div className="rounded-[2rem] bg-ink p-8 text-center text-white shadow-card"><p className="text-sm uppercase tracking-[.25em] text-white/50">Center</p><h3 className="mt-12 text-4xl font-black">BAMS Core</h3><p className="mt-4 text-white/65">One permission model. One company graph. One executive layer.</p></div><div className="grid gap-3">{replacementSystems.slice(3).map((x) => <SystemNode key={x} label={x} />)}</div></div></Reveal></section>;
}

function SystemNode({ label }: { label: string }) {
  return <MotionDiv whileHover={{ x: 6, scale: 1.02 }} className="rounded-2xl border border-slate-100 bg-white p-5 font-black shadow-card">{label}</MotionDiv>;
}

export function AiOperatingSystemSection() {
  return <section id="tour" className="px-6 py-24"><SectionHeader eyebrow="AI operating system" title="AI that reads company context, not isolated tickets." text="BAMS AI surfaces precise signals, explains the business impact, and recommends the next operating decision." /><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-3">{aiInsights.map((item, i) => <Reveal delay={(i % 3) * .06} key={item.agent} className="card-hover rounded-[2rem] border border-slate-100 bg-white p-6 shadow-card"><p className="text-sm font-black text-brand-600">{item.agent}</p><h3 className="mt-6 text-xl font-black leading-7">{item.signal}</h3><div className="mt-6 rounded-2xl bg-brand-50 p-4"><p className="text-xs font-black uppercase tracking-[.2em] text-brand-700">Recommended action</p><p className="mt-2 text-sm font-semibold text-slate-700">{item.action}</p></div></Reveal>)}</div></section>;
}

export function ProductEcosystemSection() {
  return <section id="modules" className="px-6 py-24"><SectionHeader eyebrow="Product ecosystem" title="Modules connected by the same operating model." text="Each BAMS product shares identity, permissions, approvals, analytics, and AI context, so adding a module strengthens the entire system." /><div className="mx-auto max-w-7xl rounded-[2.5rem] bg-white p-6 shadow-card"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{modules.map((m, i) => <Reveal delay={(i % 4) * .04} key={m} className="rounded-3xl border border-slate-100 bg-gradient-to-br from-white to-slate-50 p-6"><div className="mb-8 h-1 w-16 rounded-full bg-gradient-to-r from-brand-600 to-violet" /><h3 className="text-xl font-black">{m}</h3><p className="mt-2 text-sm text-muted">Connected to BAMS Core, executive reporting, and governed AI.</p></Reveal>)}</div></div></section>;
}

export function ExecutiveSection() {
  return <section className="px-6 py-24"><SectionHeader eyebrow="Executive dashboards" title="Boardroom data without waiting for a reporting cycle." text="CEO, CFO, COO, and CHRO views are built from the same operating data used by frontline teams." /><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-2">{dashboards.map((dash, i) => <Reveal delay={i * .06} key={dash.title} className="card-hover rounded-[2rem] bg-white p-7 shadow-card"><p className="font-black text-brand-600">{dash.title} Dashboard</p><div className="mt-5 grid grid-cols-2 gap-3">{dash.metrics.map((metric, index) => <div key={metric} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-muted">{metric}</p><p className="mt-2 text-2xl font-black">{dash.values[index]}</p></div>)}</div><div className="mt-4 h-24 rounded-3xl bg-gradient-to-r from-brand-50 via-white to-violet/10" /></Reveal>)}</div></section>;
}

export function IndustrySection() {
  return <section className="px-6 py-24"><SectionHeader eyebrow="Industry solutions" title="Designed for companies where workforce decisions affect the P&L." text="BAMS adapts to distributed teams, shift-heavy workforces, regulated environments, and fast-growing operating models." /><div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-3">{industries.map((x) => <div key={x} className="glass card-hover rounded-3xl p-7 text-2xl font-black">{x}</div>)}</div></section>;
}

export function IntegrationsSection() {
  return <section className="px-6 py-24"><SectionHeader eyebrow="Integrations" title="Connect the systems that still need to stay." text="BAMS becomes the governed operating layer across productivity, messaging, payments, calendars, and identity." /><div className="mx-auto flex max-w-5xl flex-wrap justify-center gap-4">{integrations.map((x) => <span key={x} className="rounded-full border border-slate-200 bg-white px-6 py-4 font-black shadow-card">{x}</span>)}</div></section>;
}

export function OutcomesSection() {
  return <section className="px-6 py-24"><SectionHeader eyebrow="Customer outcomes" title="Business results from one operating layer." text="BAMS is measured by how much clearer the company becomes when teams stop maintaining separate realities." /><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{outcomes.map((story) => <div key={story.company} className="rounded-3xl bg-white p-8 shadow-card"><p className="text-sm font-black text-brand-600">{story.company}</p><h3 className="mt-5 text-2xl font-black leading-8">{story.result}</h3><p className="mt-6 text-sm font-semibold text-muted">{story.proof}</p></div>)}</div></section>;
}

export function PricingSection() {
  return <section id="pricing" className="px-6 py-24"><SectionHeader eyebrow="Pricing" title="Choose the operating model that fits your stage." text="Start with the systems creating the most friction. Expand into the full Enterprise OS when the company is ready." /><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{pricing.map((p, i) => <Reveal delay={i * .08} key={p.name} className={`card-hover rounded-[2rem] p-8 shadow-card ${i === 1 ? "bg-ink text-white" : "bg-white"}`}><h3 className="text-2xl font-black">{p.name}</h3><p className="mt-6 text-5xl font-black">{p.price}</p><p className={`mt-3 min-h-20 ${i === 1 ? "text-white/60" : "text-muted"}`}>{p.copy}</p><button className={`mt-8 w-full rounded-full py-4 font-black ${i === 1 ? "bg-white text-ink" : "bg-brand-600 text-white"}`}>{i === 2 ? "Talk to Sales" : `Choose ${p.name}`}</button></Reveal>)}</div></section>;
}

export function FaqSection() {
  return <section className="px-6 py-24"><SectionHeader eyebrow="FAQ" title="Answers for enterprise buyers." text="Question, answer, and proof for teams comparing HRMS, payroll, attendance, recruiting, and workforce management platforms." /><div className="mx-auto max-w-4xl space-y-4">{faqs.map((f) => <details key={f.question} className="rounded-3xl bg-white p-6 shadow-card"><summary className="cursor-pointer text-lg font-black">{f.question}</summary><p className="mt-4 text-muted"><strong>Answer:</strong> {f.answer}</p><p className="mt-3 text-sm font-semibold text-brand-700">Supporting proof: {f.proof}</p></details>)}</div></section>;
}

export function FinalCta() {
  return <section id="demo" className="px-6 py-24"><Reveal className="mx-auto max-w-6xl rounded-[3rem] bg-gradient-to-br from-ink to-brand-700 p-10 text-center text-white shadow-glow md:p-20"><p className="font-black uppercase tracking-[.25em] text-white/50">Digital headquarters for BAMS</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">See the operating system behind your company.</h2><p className="mx-auto mt-6 max-w-2xl text-lg text-white/70">Book a demo, get a custom plan, or speak with sales about replacing fragmented workforce software.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a className="rounded-full bg-white px-8 py-4 font-black text-ink" href="mailto:demo@bams.ai">Book Demo</a><a className="rounded-full border border-white/20 px-8 py-4 font-black text-white" href="mailto:sales@bams.ai">Talk to Sales</a><a className="rounded-full border border-white/20 px-8 py-4 font-black text-white" href="mailto:plans@bams.ai">Get Custom Plan</a></div></Reveal></section>;
}
