import { aiAgents, blogCategories, faqs, featurePages, industries } from "@/data/site";
import { EnterpriseDashboard } from "@/components/DashboardMockups";
import { MotionDiv, Reveal } from "@/components/Motion";
import { Button } from "@/components/ui/Button";

export function PageHero({ eyebrow, title, text, primary = "Book Demo", href = "/book-demo" }: { eyebrow: string; title: string; text: string; primary?: string; href?: string }) {
  return <section className="relative overflow-hidden px-6 pb-20 pt-36 md:pt-44"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_10%,#d9edff,transparent_30%),radial-gradient(circle_at_80%_15%,rgba(139,92,246,.18),transparent_28%)]" /><div className="absolute inset-0 bg-grid bg-[length:44px_44px] opacity-50" /><Reveal className="relative mx-auto max-w-5xl text-center"><p className="mb-4 text-sm font-black uppercase tracking-[.25em] text-brand-600">{eyebrow}</p><h1 className="gradient-text text-5xl font-black tracking-[-.05em] md:text-7xl">{title}</h1><p className="mx-auto mt-6 max-w-3xl text-xl leading-9 text-muted">{text}</p><div className="mt-8 flex justify-center gap-3"><Button href={href}>{primary}</Button><Button href="/pricing" variant="secondary">View Pricing</Button></div></Reveal></section>;
}

export function SectionHeader({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) {
  return <Reveal className="mx-auto mb-12 max-w-3xl text-center"><p className="mb-3 text-sm font-black uppercase tracking-[.25em] text-brand-600">{eyebrow}</p><h2 className="text-3xl font-black tracking-tight md:text-5xl">{title}</h2><p className="mt-5 text-lg leading-8 text-muted">{text}</p></Reveal>;
}

export function TrustedCompanies() { return <section className="px-6 py-16"><Reveal className="mx-auto max-w-7xl"><p className="text-center text-sm font-bold uppercase tracking-[.2em] text-muted">Trusted by operating teams scaling globally</p><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-6">{["Aster", "Northstar", "Helio", "Vertex", "Kinetic", "Mosaic"].map(l=><div className="glass rounded-2xl py-6 text-center text-xl font-black text-slate-500" key={l}>{l}</div>)}</div></Reveal></section>; }

export function ProblemStory() { return <section className="px-6 py-20"><SectionHeader eyebrow="The fragmentation tax" title="Companies do not fail from lack of tools. They fail from disconnected work." text="BAMS replaces scattered approvals, duplicate records, hidden documents, manual payroll checks and leadership guesswork with one intelligent operating layer." /><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{["Data trapped in silos", "Manual approvals everywhere", "Leaders see lagging reports"].map((p,i)=><Reveal delay={i*.08} key={p} className="card-hover rounded-[2rem] border border-slate-100 bg-white p-8 shadow-card"><span className="text-4xl">{["🧩","⏳","📉"][i]}</span><h3 className="mt-6 text-2xl font-black">{p}</h3><p className="mt-3 text-muted">Teams lose context switching between HR, finance, sales and service systems.</p></Reveal>)}</div></section>; }

export function WhyBams() { return <section className="px-6 py-20"><SectionHeader eyebrow="Why BAMS" title="A company operating system, not another point tool." text="Every workflow shares a common graph of people, money, customers, documents and decisions." /><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-4">{["Unified data model", "Permission-aware AI", "Executive command center", "Composable workflows"].map((x,i)=><MotionDiv whileHover={{ y: -6 }} className="rounded-3xl bg-white p-7 shadow-card" key={x}><p className="text-sm font-black text-brand-600">0{i+1}</p><h3 className="mt-8 text-xl font-black">{x}</h3><p className="mt-3 text-sm text-muted">Designed for enterprise scale, auditability and day-to-day operator speed.</p></MotionDiv>)}</div></section>; }

export function AIOperatingSystem() { return <section className="px-6 py-20"><SectionHeader eyebrow="AI operating system" title="AI copilots that understand how your company actually works." text="Role-aware copilots answer questions, route work, detect exceptions and recommend next best actions." /><div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-5">{aiAgents.map((a,i)=><Reveal delay={i*.05} className="rounded-3xl bg-gradient-to-br from-white to-brand-50 p-6 shadow-card" key={a}><div className="grid h-12 w-12 place-items-center rounded-2xl bg-ink text-white">✦</div><h3 className="mt-8 text-xl font-black">{a}</h3><p className="mt-3 text-sm text-muted">Secure answers and actions grounded in live operating context.</p></Reveal>)}</div></section>; }

export function ProductEcosystem() { return <section className="px-6 py-20"><SectionHeader eyebrow="Product ecosystem" title="One suite for every operating rhythm." text="Launch with a single workflow or transform the entire back office from hire to retire and lead to cash." /><div className="mx-auto grid max-w-7xl gap-4 sm:grid-cols-2 lg:grid-cols-4">{featurePages.map(([m,slug,desc],i)=><Reveal delay={(i%4)*.05} key={slug} className="card-hover rounded-3xl border border-slate-100 bg-white p-6 shadow-card"><div className="mb-10 h-12 w-12 rounded-2xl bg-gradient-to-br from-brand-100 to-violet/20"/><h3 className="text-xl font-black">{m}</h3><p className="mt-2 text-sm text-muted">{desc}</p><a className="mt-5 inline-flex text-sm font-black text-brand-600" href={`/features/${slug}`}>Explore →</a></Reveal>)}</div></section>; }

export function ExecutiveDashboards() { return <section className="px-6 py-20"><SectionHeader eyebrow="Executive dashboards" title="Board-ready clarity for every leader." text="Personalized command centers for strategic, financial, operational and people decisions." /><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2">{["CEO", "CFO", "COO", "CHRO"].map((e,i)=><Reveal delay={i*.06} key={e} className="card-hover rounded-[2rem] bg-white p-7 shadow-card"><p className="font-black text-brand-600">{e} Dashboard</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Revenue","Headcount","Attrition","Payroll","Hiring","Productivity"].map((k,j)=><div className="rounded-2xl bg-slate-50 p-4" key={k}><p className="text-xs text-muted">{k}</p><p className="mt-2 font-black">{["$8.4M","2,418","6.2%","99.1%","42","91%"][j]}</p></div>)}</div></Reveal>)}</div></section>; }

export function IndustrySolutions() { return <section className="px-6 py-20"><SectionHeader eyebrow="Industries" title="Purpose-built for complex operating models." text="Configurable templates make BAMS fit regulated, distributed and high-growth environments." /><div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-3">{industries.map(([x,slug,desc])=><a href={`/industries/${slug}`} key={slug} className="glass card-hover rounded-3xl p-7"><h3 className="text-2xl font-black">{x}</h3><p className="mt-3 text-sm text-muted">{desc}</p></a>)}</div></section>; }

export function Integrations() { return <section className="px-6 py-20"><SectionHeader eyebrow="Integrations" title="Connect the systems your teams already trust." text="BAMS becomes the intelligent control plane across productivity, accounting, payments and messaging." /><div className="mx-auto flex max-w-5xl flex-wrap justify-center gap-4">{["Google Workspace", "Microsoft 365", "WhatsApp", "Razorpay", "Tally", "Zoho Books", "Slack", "Okta", "Jira"].map(x=><span key={x} className="rounded-full border border-slate-200 bg-white px-6 py-4 font-black shadow-card">{x}</span>)}</div></section>; }

export function Pricing() { const plans = [["Starter","$9","Start Free Trial","/signup?plan=starter"],["Growth","$19","Book Demo","/book-demo"],["Enterprise","Custom","Contact Sales","/contact?intent=sales"]]; return <section className="px-6 py-20"><SectionHeader eyebrow="Pricing" title="Start focused. Scale into the full operating system." text="Transparent packages for teams modernizing operations, with enterprise controls when you need them." /><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{plans.map(([p,price,cta,href],i)=><Reveal delay={i*.08} key={p} className={`card-hover rounded-[2rem] p-8 shadow-card ${i===1?"bg-ink text-white":"bg-white"}`}><h3 className="text-2xl font-black">{p}</h3><p className="mt-6 text-5xl font-black">{price}</p><p className={`mt-3 ${i===1?"text-white/60":"text-muted"}`}>per employee / month</p><Button className="mt-8 w-full" variant={i===1?"secondary":"primary"} href={href}>{cta}</Button></Reveal>)}</div></section>; }

export function CustomerStories() { return <section className="px-6 py-20"><SectionHeader eyebrow="Customer stories" title="Operators finally get one source of truth." text="High-growth companies use BAMS to make work visible, measurable and intelligently automated." /><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{["BAMS turned HR, finance and sales reviews into one weekly operating ritual.", "The AI copilot saves managers hours every week and keeps approvals moving.", "It feels like Linear for company operations: fast, elegant and deeply connected."].map((q,i)=><a href="/case-studies" key={q} className="rounded-3xl bg-white p-8 shadow-card"><p className="text-lg leading-8">“{q}”</p><p className="mt-6 font-black">{["Maya Rao", "Ethan Cole", "Sara Lin"][i]}</p><p className="text-sm text-muted">COO, demo customer</p></a>)}</div></section>; }

export function FAQ() { return <section className="px-6 py-20"><SectionHeader eyebrow="FAQ" title="Questions before your operating system upgrade?" text="Everything you need to know for a confident pilot." /><div className="mx-auto max-w-4xl space-y-4">{faqs.map(([q,a])=><details key={q} className="rounded-3xl bg-white p-6 shadow-card"><summary className="cursor-pointer text-lg font-black">{q}</summary><p className="mt-4 text-muted">{a}</p></details>)}</div></section>; }

export function FinalCTA() { return <section className="px-6 py-24"><Reveal className="mx-auto max-w-6xl rounded-[3rem] bg-gradient-to-br from-ink to-brand-700 p-10 text-center text-white shadow-glow md:p-20"><p className="font-black uppercase tracking-[.25em] text-white/50">Build with BAMS</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Build a company that runs itself smarter every day.</h2><p className="mx-auto mt-6 max-w-2xl text-lg text-white/70">Book a demo and experience the AI powered operating system for modern enterprises.</p><Button className="mt-9" variant="secondary" href="/book-demo">Book Demo</Button></Reveal></section>; }

export function BlogGrid() { return <div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3">{blogCategories.map((c,i)=><article className="rounded-3xl bg-white p-7 shadow-card" key={c}><p className="text-sm font-black text-brand-600">{c}</p><h3 className="mt-5 text-2xl font-black">{c} operating playbook for AI-era companies</h3><p className="mt-3 text-muted">Practical guidance for teams unifying systems, workflows and executive visibility.</p><a className="mt-6 inline-flex font-black text-brand-600" href={`/blog/${c.toLowerCase().replaceAll(" ", "-")}`}>Read article →</a></article>)}</div>; }

export function DashboardShowcase() { return <section className="px-6 py-20"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><SectionHeader eyebrow="Live command center" title="A realistic operating cockpit for every business moment." text="BAMS blends workforce, revenue, payroll, hiring and productivity signals into a single executive system." /></div><EnterpriseDashboard /></div></section>; }
